### ISSUE TITLE
Change color/text of return button

### ISSUE THREAD

**Issue by MaKleSoft** [don/KeyboardToolbarRemover#1]
First of all, thanks for this great plugin! I can't believe it doesn't have more stars! Now since you are the only one I know who actually got this to work properly, do you by any chance know how to change the appearance of the return button in a phonegap app? That would be the icing on the cake...

**Comment by jeroencoumans** [comment]
If you use a form with an input, the keyboard will show a blue "Go" button instead.

**Comment by MaKleSoft** [comment]
Yeah, I know that. unfortunately this is not an option for me as a tap on the Go button will reload the page. Thanks for your answer, anyway!

**Comment by tschoffelen** [comment]
Simply add onsubmit="return false;" to the <form> element to cancel the form action.

**Comment by MaKleSoft** [comment]
Already figured that out. But thanks! I guess we can close this issue now.
