### ISSUE TITLE
Keyboard.hide() opening keybord moves viewport

### ISSUE THREAD

**Issue by rolandschuetz** [don/KeyboardToolbarRemover#10]
Hello,

on iOS 6 in a phonegap 3.3.0 container the viewport moves up and down when the keyboard opens and toolbar.hide() was applied before.

Any idea how to fix that?

Thanks,
Roland

**Comment by don** [comment]
@rolandschuetz since you're using Cordova 3.3, you might have better luck with the new iOS keyboard plugin https://github.com/apache/cordova-plugins/tree/master/keyboard which has better resizing logic

**Comment by rolandschuetz** [comment]
Thanks for link, I'll check it out!
