### ISSUE TITLE
Black box behind the toolbar

### ISSUE THREAD

**Issue by nikilster** [don/KeyboardToolbarRemover#11]
I'm seeing this:  https://www.dropbox.com/s/hzppvg8bhgp0dsr/Screenshot%202014-03-02%2017.38.27.png

iOs 7 emulator.  Thoughts?

**Comment by don** [comment]
That's an unfortunate resizing issue. Are you using Cordova 3.3+? Shazron's new keyboard plugin has much better resizing logic https://github.com/apache/cordova-plugins/tree/master/keyboard  See if that works better with your code.
