### ISSUE TITLE
Can the main button be replaced by anything other than "return"?

### ISSUE THREAD

**Issue by marekhrabe** [don/KeyboardToolbarRemover#12]
I'm talking about the bottom right button that is normally replaced by "Go" or "Search" buttons on iOS. Or does this work already? I haven't tested it yet

**Comment by don** [comment]
See #1 for how people have made it say "Go". 

This plugin is almost obsolete. I think you're better off with the newer https://github.com/apache/cordova-plugins/tree/master/keyboard
