### ISSUE TITLE
iOS 8

### ISSUE THREAD

**Issue by julesmoretti** [don/KeyboardToolbarRemover#15]
Hello. Sorry to bother but I am unable to see a successful result with it.

I have tried adding the following in my `config.xml` just before the `</widget>`:

```
<plugin name="KeyboardToolbarRemover" value="KeyboardToolbarRemover" />
```

As well as included:
toolbar.hide()

within my controller after a function onDeviceReady() but no result.

Any help with this would be awesome.

Thank you.

**Comment by don** [comment]
This plugin is dead. You're better off using https://github.com/apache/cordova-plugins/tree/master/keyboard or one of the newer plugins that has better support for newer versions of iOS.
