### ISSUE TITLE
just hide next and prev button 

### ISSUE THREAD

**Issue by nolinq** [don/KeyboardToolbarRemover#2]
thank u for this wdf plugin!
but i have a problem about this toolbar
i want just hide next and prev button ,how can i do ?

**Comment by don** [comment]
This plugin just removes the toolbar.

Theoretically you could write a similar plugin to find the UIWebFormAccessory and then instead of removing the UIWebFormAccessory, find the previous and next buttons and remove them.

**Comment by edvenkat** [comment]
Wow Awesome plugin. It  is really useful for me.

How to find the previous and next button??? could you please provide the code for that?????
